version: "3"
services:
  app:
    build: .
    working_dir: /app
    command: poetry run flask run --host=0.0.0.0
    environment:
      - APP_SETTINGS=security_checker.config.DevelopmentConfig
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://docker:docker@pg/docker
    volumes:
      - ".:/app"
    ports:
      - "5000:5000"
    depends_on:
      - pg
  pg:
    image: postgres:14
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./db/dumps:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local